version: 2
paths-ignore:
  - logs/**
  - "**/*.jsonl"
  - "**/*.log"
  - .venv/**paths-ignore:
  - logs/**
  - data/**
  - "**/*.jsonl"
  - "**/*.log"
  - .venv/**
  - mawi/**
  - datasets/**
  - backups/**
