CXX = g++
CXXFLAGS = -std=c++20 -Wall -Wextra -O2
LDFLAGS = -lzmq

SRC1 = service1/main.cpp
SRC2 = service2/main.cpp
BIN_DIR = bin
BIN1 = $(BIN_DIR)/service1_exe
BIN2 = $(BIN_DIR)/service2_exe

all: $(BIN_DIR) $(BIN1) $(BIN2)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

$(BIN1): $(SRC1)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(BIN2): $(SRC2)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

run: all
	@echo "🚀 Starting server in background..."
	./$(BIN1) & \
	SERVER_PID=$$!; \
	sleep 1; \
	echo "📤 Running client..."; \
	./$(BIN2); \
	kill $$SERVER_PID

clean:
	rm -rf $(BIN_DIR)

.PHONY: all run clean