#!/usr/bin/env python3
"""
ML Defender - RandomForest C++20 Code Generator
Generates inline constexpr C++ code from complete_forest_100_trees.json
Author: Alonso + Claude (Co-authored)
"""

import json
import sys
from pathlib import Path
from typing import Dict, List, Any

def load_forest_json(json_path: str) -> Dict[str, Any]:
    """Load and validate the complete forest JSON"""
    print(f"📂 Loading forest from: {json_path}")
    with open(json_path, 'r') as f:
        data = json.load(f)

    # Validate structure
    assert 'model_info' in data, "Missing model_info"
    assert 'complete_forest' in data, "Missing complete_forest"
    assert data['model_info']['n_trees'] == 100, "Expected 100 trees"
    assert data['model_info']['n_features'] == 10, "Expected 10 features"

    print(f"✅ Validated: {data['model_info']['n_trees']} trees, "
          f"{data['model_info']['n_features']} features")
    return data

def extract_leaf_value(value_array: List) -> tuple[float, float]:
    """Extract [P(benign), P(ransomware)] from [[benign, ransomware]] structure"""
    # Structure is consistently [[benign_prob, ransomware_prob]]
    return float(value_array[0][0]), float(value_array[0][1])

def debug_tree_structure(forest_data: Dict[str, Any]):
    """Debug function to inspect tree structure"""
    complete_forest = forest_data['complete_forest']
    tree_0 = complete_forest['tree_0']

    print("🔍 Debugging tree structure:")
    print(f"  Tree keys: {list(tree_0.keys())}")
    print(f"  n_nodes: {tree_0['n_nodes']}")
    print(f"  value[0] type: {type(tree_0['value'][0])}")
    print(f"  value[0] content: {tree_0['value'][0]}")

    # Check first few values
    for i in range(min(5, tree_0['n_nodes'])):
        print(f"  value[{i}]: {tree_0['value'][i]} (type: {type(tree_0['value'][i])})")

def generate_tree_nodes(tree_data: Dict[str, Any], tree_id: int) -> str:
    """Generate C++ TreeNode array for a single tree"""
    n_nodes = tree_data['n_nodes']
    children_left = tree_data['children_left']
    children_right = tree_data['children_right']
    features = tree_data['feature']
    thresholds = tree_data['threshold']
    values = tree_data['value']

    cpp_code = f"// Tree {tree_id}: {n_nodes} nodes\n"
    cpp_code += f"inline constexpr TreeNode tree_{tree_id}[] = {{\n"

    for i in range(n_nodes):
        feature_idx = features[i]
        threshold = thresholds[i]
        left = children_left[i]
        right = children_right[i]
        benign_prob, ransomware_prob = extract_leaf_value(values[i])

        # Format node
        cpp_code += f"    {{{feature_idx}, {threshold:.10f}f, {left}, {right}, "
        cpp_code += f"{{{benign_prob:.10f}f, {ransomware_prob:.10f}f}}}}"

        if i < n_nodes - 1:
            cpp_code += ","

        # Add comment for readability
        if feature_idx == -2:
            cpp_code += f"  // Leaf: P(ransomware)={ransomware_prob:.4f}"
        else:
            feature_names = [
                "io_intensity", "entropy", "resource_usage", "network_activity",
                "file_operations", "process_anomaly", "temporal_pattern",
                "access_frequency", "data_volume", "behavior_consistency"
            ]
            fname = feature_names[feature_idx] if feature_idx < 10 else "unknown"
            cpp_code += f"  // {fname} <= {threshold:.4f}?"

        cpp_code += "\n"

    cpp_code += "};\n\n"
    return cpp_code

def generate_forest_header(forest_data: Dict[str, Any], output_path: str):
    """Generate complete forest_trees_inline.hpp"""
    complete_forest = forest_data['complete_forest']
    model_info = forest_data['model_info']

    print(f"🔧 Generating C++ header: {output_path}")

    with open(output_path, 'w') as f:
        # Header guard and includes
        f.write("// AUTO-GENERATED by generate_cpp_forest.py\n")
        f.write("// DO NOT EDIT MANUALLY\n")
        f.write("// Source: complete_forest_100_trees.json\n")
        f.write(f"// Trees: {model_info['n_trees']}\n")
        f.write(f"// Features: {model_info['n_features']}\n\n")

        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")

        f.write("namespace ml_defender::detail {\n\n")

        # TreeNode struct
        f.write("/// RandomForest tree node (decision or leaf)\n")
        f.write("struct TreeNode {\n")
        f.write("    int16_t feature_idx;    // Feature index, -2 if leaf\n")
        f.write("    float threshold;        // Split threshold, -2.0 if leaf\n")
        f.write("    int32_t left_child;     // Left child index, -1 if leaf\n")
        f.write("    int32_t right_child;    // Right child index, -1 if leaf\n")
        f.write("    float value[2];         // [P(benign), P(ransomware)]\n")
        f.write("};\n\n")

        # Generate all 100 trees
        total_nodes = 0
        tree_sizes = []

        for tree_id in range(100):
            tree_key = f"tree_{tree_id}"
            tree_data = complete_forest[tree_key]
            tree_sizes.append(tree_data['n_nodes'])
            total_nodes += tree_data['n_nodes']

            tree_code = generate_tree_nodes(tree_data, tree_id)
            f.write(tree_code)

            if (tree_id + 1) % 10 == 0:
                print(f"  ✅ Generated trees 0-{tree_id} ({total_nodes} nodes so far)")

        # Array of tree pointers
        f.write("/// Array of pointers to all trees\n")
        f.write("inline constexpr const TreeNode* all_trees[] = {\n")
        for i in range(100):
            f.write(f"    tree_{i}")
            if i < 99:
                f.write(",")
            if (i + 1) % 5 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Tree sizes array
        f.write("/// Number of nodes in each tree\n")
        f.write("inline constexpr size_t tree_sizes[] = {\n")
        for i in range(100):
            f.write(f"    {tree_sizes[i]}")
            if i < 99:
                f.write(",")
            if (i + 1) % 10 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Constants
        f.write(f"inline constexpr size_t NUM_TREES = {model_info['n_trees']};\n")
        f.write(f"inline constexpr size_t NUM_FEATURES = {model_info['n_features']};\n")
        f.write(f"inline constexpr size_t TOTAL_NODES = {total_nodes};\n\n")

        f.write("} // namespace ml_defender::detail\n")

    print(f"✅ Generated header: {total_nodes} total nodes across 100 trees")
    print(f"📊 Average nodes per tree: {total_nodes / 100:.1f}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python generate_cpp_forest.py <input_json> <output_hpp>")
        print("Example: python generate_cpp_forest.py complete_forest_100_trees.json forest_trees_inline.hpp")
        sys.exit(1)

    input_json = sys.argv[1]
    output_hpp = sys.argv[2]

    # Load and validate
    forest_data = load_forest_json(input_json)

    # Debug: inspect structure
    debug_tree_structure(forest_data)

    # Generate C++ header
    generate_forest_header(forest_data, output_hpp)

    print(f"\n🎉 SUCCESS! Generated: {output_hpp}")
    print(f"📏 File size: ~{Path(output_hpp).stat().st_size / 1024:.1f} KB")
    print(f"\n💡 Next steps:")
    print(f"  1. Move {output_hpp} to src/ml_defender/")
    print(f"  2. Compile with C++20: g++ -std=c++20 -O3 -march=native")
    print(f"  3. Include in ransomware_detector.cpp")

if __name__ == '__main__':
    main()