import json
import pickle
import sys
from pathlib import Path
from typing import Dict, List, Any

def load_traffic_model(model_path: str, dataset_path: str):
    """Carga el modelo y metadata"""
    print(f"📂 Loading model from: {model_path}")

    with open(model_path, 'rb') as f:
        model = pickle.load(f)

    with open(dataset_path, 'r') as f:
        dataset_info = json.load(f)

    print(f"✅ Model loaded: {model.n_estimators} trees, {dataset_info['model_info']['n_features']} features")
    return model, dataset_info

def extract_tree_structure(forest_model, feature_names):
    """Extrae la estructura de todos los árboles del RandomForest"""
    print("🌳 Extracting tree structures...")

    complete_forest = {}
    for i, estimator in enumerate(forest_model.estimators_):
        tree = estimator.tree_

        tree_data = {
            'n_nodes': tree.node_count,
            'children_left': tree.children_left.tolist(),
            'children_right': tree.children_right.tolist(),
            'feature': tree.feature.tolist(),
            'threshold': tree.threshold.tolist(),
            'value': tree.value.tolist()  # Probabilidades por clase
        }
        complete_forest[f'tree_{i}'] = tree_data

        if (i + 1) % 10 == 0:
            print(f"  ✅ Processed {i + 1} trees")

    return complete_forest

def generate_traffic_cpp_header(forest_data, dataset_info, output_path: str):
    """Genera el header C++20 para el modelo de tráfico"""
    print(f"🔧 Generating C++ header: {output_path}")

    model_info = dataset_info['model_info']

    # CORRECCIÓN: Usar open() y close() explícitamente en lugar de with open()
    f = open(output_path, 'w')

    try:
        # Header
        f.write("// AUTO-GENERATED by GenerateTrafficCPPForest.py\n")
        f.write("// Traffic Classification Model - Internet vs Internal\n")
        f.write(f"// Trees: {len(forest_data)}\n")
        f.write(f"// Features: {model_info['n_features']}\n")
        f.write(f"// Classes: {model_info['classes']}\n\n")

        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <cstddef>\n\n")

        f.write("namespace ml_defender::traffic {\n\n")

        # TreeNode struct (similar al ransomware)
        f.write("struct TrafficTreeNode {\n")
        f.write("    int16_t feature_idx;    // Feature index, -2 if leaf\n")
        f.write("    float threshold;        // Split threshold\n")
        f.write("    int32_t left_child;     // Left child index\n")
        f.write("    int32_t right_child;    // Right child index\n")
        f.write("    float value[2];         // [P(internet), P(internal)]\n")
        f.write("};\n\n")

        # Generar todos los árboles
        total_nodes = 0
        tree_sizes = []

        for tree_id in range(len(forest_data)):
            tree_key = f"tree_{tree_id}"
            tree_data = forest_data[tree_key]
            tree_sizes.append(tree_data['n_nodes'])
            total_nodes += tree_data['n_nodes']

            # Generar código para este árbol
            f.write(f"// Tree {tree_id}: {tree_data['n_nodes']} nodes\n")
            f.write(f"inline constexpr TrafficTreeNode {tree_key}[] = {{\n")

            for i in range(tree_data['n_nodes']):
                feature_idx = tree_data['feature'][i]
                threshold = tree_data['threshold'][i]
                left = tree_data['children_left'][i]
                right = tree_data['children_right'][i]

                # Extraer probabilidades (normalizar valores)
                node_values = tree_data['value'][i][0]
                total = sum(node_values)
                prob_internet = node_values[0] / total
                prob_internal = node_values[1] / total

                f.write(f"    {{{feature_idx}, {threshold:.10f}f, {left}, {right}, ")
                f.write(f"{{{prob_internet:.10f}f, {prob_internal:.10f}f}}}}")

                if i < tree_data['n_nodes'] - 1:
                    f.write(",")

                # Comentario descriptivo
                if feature_idx == -2:
                    f.write(f"  // Leaf: P(internal)={prob_internal:.4f}")
                else:
                    feature_name = model_info['feature_names'][feature_idx] if feature_idx >= 0 else "leaf"
                    f.write(f"  // {feature_name} <= {threshold:.4f}?")

                f.write("\n")

            f.write("};\n\n")

            if (tree_id + 1) % 10 == 0:
                print(f"  ✅ Generated trees 0-{tree_id} ({total_nodes} nodes so far)")

        # Array de punteros a árboles
        f.write("// Array of pointers to all trees\n")
        f.write("inline constexpr const TrafficTreeNode* traffic_trees[] = {\n")
        for i in range(len(forest_data)):
            f.write(f"    tree_{i}")
            if i < len(forest_data) - 1:
                f.write(",")
            if (i + 1) % 5 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Tamaños de árboles
        f.write("// Number of nodes in each tree\n")
        f.write("inline constexpr size_t traffic_tree_sizes[] = {\n")
        for i in range(len(forest_data)):
            f.write(f"    {tree_sizes[i]}")
            if i < len(forest_data) - 1:
                f.write(",")
            if (i + 1) % 10 == 0:
                f.write("\n")
        f.write("};\n\n")

        # Constantes
        f.write(f"inline constexpr size_t TRAFFIC_NUM_TREES = {len(forest_data)};\n")
        f.write(f"inline constexpr size_t TRAFFIC_NUM_FEATURES = {model_info['n_features']};\n")
        f.write(f"inline constexpr size_t TRAFFIC_TOTAL_NODES = {total_nodes};\n\n")

        # CORRECCIÓN: AÑADIR PREDICT FUNCTION DENTRO del archivo abierto
        f.write("""/// Traffic Classification Prediction Function  
/// @param features Array of feature values
/// @return Probability of INTERNAL traffic (0.0 to 1.0)
inline float predict_traffic(const float features[TRAFFIC_NUM_FEATURES]) {
    float internet_prob = 0.0f;
    float internal_prob = 0.0f;
    
    for (size_t tree_idx = 0; tree_idx < TRAFFIC_NUM_TREES; ++tree_idx) {
        const TrafficTreeNode* tree = traffic_trees[tree_idx];
        size_t node_idx = 0;
        
        while (true) {
            const auto& node = tree[node_idx];
            
            if (node.feature_idx == -2) { // Leaf node
                internet_prob += node.value[0];
                internal_prob += node.value[1];
                break;
            }
            
            if (features[node.feature_idx] <= node.threshold) {
                node_idx = node.left_child;
            } else {
                node_idx = node.right_child;
            }
        }
    }
    
    // Return probability of INTERNAL traffic (class 1)
    return internal_prob / TRAFFIC_NUM_TREES;
}

} // namespace ml_defender::traffic
""")

    finally:
        # Cerrar archivo explícitamente
        f.close()

    print(f"✅ Generated header: {total_nodes} total nodes across {len(forest_data)} trees")
    print(f"📊 Average nodes per tree: {total_nodes / len(forest_data):.1f}")

def main():
    if len(sys.argv) != 3:
        print("Usage: python GenerateTrafficCPPForest.py <input_pkl> <output_hpp>")
        print("Example: python GenerateTrafficCPPForest.py traffic_classification_model.pkl traffic_trees_inline.hpp")
        sys.exit(1)

    input_pkl = sys.argv[1]
    input_json = "traffic_classification_dataset.json"  # Asume mismo directorio
    output_hpp = sys.argv[2]

    # Cargar modelo y datos
    model, dataset_info = load_traffic_model(input_pkl, input_json)

    # Extraer estructura del bosque
    forest_data = extract_tree_structure(model, dataset_info['model_info']['feature_names'])

    # Generar header C++
    generate_traffic_cpp_header(forest_data, dataset_info, output_hpp)

    print(f"\n🎉 SUCCESS! Generated: {output_hpp}")
    print(f"💡 Next: Include in your traffic classifier C++ code")

if __name__ == '__main__':
    main()